### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Quantium** [mercadopago/dx-nodejs#134]
**Description**

When I try to install it vía npm library or even directly from this repo like this:

`npm install --save mercadopago` 

`npm install --save https://github.com/mercadopago/dx-nodejs.git`

I got the following **error**:

`Unexpected end of JSON input while parsing near '...nt-env":"latest","gru'`

**Expected behavior**
To install the module...

**Screenshots**

<img width="1372" alt="pic 2019-03-11 at 3 51 52 PM" src="https://user-images.githubusercontent.com/2090436/54160716-e516f600-4415-11e9-95d4-7b2e73bc4530.png">

**Server**

- **OS:** MacOS Mojave
- **node** --version: v11.10.0
- **npm** --version: 6.9.0

**Additional context**

This is my full _.npm/_logs/2019-03-11T21_37_27_225Z-debug.log_ file
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/mercadopago/dx-nodejs.git' ]
2 info using npm@6.9.0
3 info using node@v11.10.0
4 verbose npm-session 1518d2b11f68ad55
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 info lifecycle mercadopago@1.0.22~prepack: mercadopago@1.0.22
8 info lifecycle mercadopago@1.0.22~postpack: mercadopago@1.0.22
9 silly pacote git manifest for undefined@git+https://github.com/mercadopago/dx-nodejs.git fetched in 2805ms
10 timing stage:loadCurrentTree Completed in 3024ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 96ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule mercadopago@1.0.22 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/uuid 861ms (from cache)
19 silly pacote version manifest for uuid@3.0.1 fetched in 863ms
20 silly resolveWithNewModule uuid@3.0.1 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/moment 868ms (from cache)
22 silly fetchPackageMetaData error for moment@^2.24.0 Unexpected end of JSON input while parsing near '...nt-env":"latest","gru'
23 http fetch GET 304 https://registry.npmjs.org/ajv 875ms (from cache)
24 silly pacote version manifest for ajv@4.10.3 fetched in 883ms
25 silly resolveWithNewModule ajv@4.10.3 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/request 961ms (from cache)
27 silly pacote range manifest for request@^2.88.0 fetched in 967ms
28 silly resolveWithNewModule request@2.88.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/bluebird 1030ms (from cache)
30 silly pacote version manifest for bluebird@3.4.7 fetched in 1035ms
31 silly resolveWithNewModule bluebird@3.4.7 checking installable status
32 http fetch GET 304 https://registry.npmjs.org/request-etag 1063ms (from cache)
33 silly pacote version manifest for request-etag@2.0.3 fetched in 1064ms
34 silly resolveWithNewModule request-etag@2.0.3 checking installable status
35 timing stage:rollbackFailedOptional Completed in 1ms
36 timing stage:runTopLevelLifecycles Completed in 4202ms
37 silly saveTree mercadopago_sample@1.0.0
37 silly saveTree ├─┬ body-parser@1.18.3
37 silly saveTree │ ├── bytes@3.0.0
37 silly saveTree │ ├── content-type@1.0.4
37 silly saveTree │ ├─┬ debug@2.6.9
37 silly saveTree │ │ └── ms@2.0.0
37 silly saveTree │ ├── depd@1.1.2
37 silly saveTree │ ├─┬ http-errors@1.6.3
37 silly saveTree │ │ ├── inherits@2.0.3
37 silly saveTree │ │ ├── setprototypeof@1.1.0
37 silly saveTree │ │ └── statuses@1.4.0
37 silly saveTree │ ├─┬ iconv-lite@0.4.23
37 silly saveTree │ │ └── safer-buffer@2.1.2
37 silly saveTree │ ├─┬ on-finished@2.3.0
37 silly saveTree │ │ └── ee-first@1.1.1
37 silly saveTree │ ├── qs@6.5.2
37 silly saveTree │ ├─┬ raw-body@2.3.3
37 silly saveTree │ │ └── unpipe@1.0.0
37 silly saveTree │ └─┬ type-is@1.6.16
37 silly saveTree │   ├── media-typer@0.3.0
37 silly saveTree │   └─┬ mime-types@2.1.22
37 silly saveTree │     └── mime-db@1.38.0
37 silly saveTree ├─┬ express@4.16.4
37 silly saveTree │ ├─┬ accepts@1.3.5
37 silly saveTree │ │ └── negotiator@0.6.1
37 silly saveTree │ ├── array-flatten@1.1.1
37 silly saveTree │ ├── content-disposition@0.5.2
37 silly saveTree │ ├── cookie-signature@1.0.6
37 silly saveTree │ ├── cookie@0.3.1
37 silly saveTree │ ├── encodeurl@1.0.2
37 silly saveTree │ ├── escape-html@1.0.3
37 silly saveTree │ ├── etag@1.8.1
37 silly saveTree │ ├─┬ finalhandler@1.1.1
37 silly saveTree │ │ └── parseurl@1.3.2
37 silly saveTree │ ├── fresh@0.5.2
37 silly saveTree │ ├── merge-descriptors@1.0.1
37 silly saveTree │ ├── methods@1.1.2
37 silly saveTree │ ├── parseurl@1.3.2
37 silly saveTree │ ├── path-to-regexp@0.1.7
37 silly saveTree │ ├─┬ proxy-addr@2.0.4
37 silly saveTree │ │ ├── forwarded@0.1.2
37 silly saveTree │ │ └── ipaddr.js@1.8.0
37 silly saveTree │ ├── range-parser@1.2.0
37 silly saveTree │ ├── safe-buffer@5.1.2
37 silly saveTree │ ├─┬ send@0.16.2
37 silly saveTree │ │ ├── destroy@1.0.4
37 silly saveTree │ │ └── mime@1.4.1
37 silly saveTree │ ├── serve-static@1.13.2
37 silly saveTree │ ├── utils-merge@1.0.1
37 silly saveTree │ └── vary@1.1.2
37 silly saveTree ├─┬ jade@1.11.0
37 silly saveTree │ ├── character-parser@1.2.1
37 silly saveTree │ ├─┬ clean-css@3.4.28
37 silly saveTree │ │ ├─┬ commander@2.8.1
37 silly saveTree │ │ │ └── graceful-readlink@1.0.1
37 silly saveTree │ │ └─┬ source-map@0.4.4
37 silly saveTree │ │   └── amdefine@1.0.1
37 silly saveTree │ ├── commander@2.6.0
37 silly saveTree │ ├─┬ constantinople@3.0.2
37 silly saveTree │ │ └── acorn@2.7.0
37 silly saveTree │ ├─┬ jstransformer@0.0.2
37 silly saveTree │ │ ├── is-promise@2.1.0
37 silly saveTree │ │ └─┬ promise@6.1.0
37 silly saveTree │ │   └── asap@1.0.0
37 silly saveTree │ ├─┬ mkdirp@0.5.1
37 silly saveTree │ │ └── minimist@0.0.8
37 silly saveTree │ ├─┬ transformers@2.1.0
37 silly saveTree │ │ ├─┬ css@1.0.8
37 silly saveTree │ │ │ ├── css-parse@1.0.4
37 silly saveTree │ │ │ └── css-stringify@1.0.5
37 silly saveTree │ │ ├─┬ promise@2.0.0
37 silly saveTree │ │ │ └── is-promise@1.0.1
37 silly saveTree │ │ └─┬ uglify-js@2.2.5
37 silly saveTree │ │   ├─┬ optimist@0.3.7
37 silly saveTree │ │   │ └── wordwrap@0.0.3
37 silly saveTree │ │   └── source-map@0.1.43
37 silly saveTree │ ├─┬ uglify-js@2.8.29
37 silly saveTree │ │ ├── source-map@0.5.7
37 silly saveTree │ │ ├── uglify-to-browserify@1.0.2
37 silly saveTree │ │ └─┬ yargs@3.10.0
37 silly saveTree │ │   ├── camelcase@1.2.1
37 silly saveTree │ │   ├─┬ cliui@2.1.0
37 silly saveTree │ │   │ ├─┬ center-align@0.1.3
37 silly saveTree │ │   │ │ ├─┬ align-text@0.1.4
37 silly saveTree │ │   │ │ │ ├─┬ kind-of@3.2.2
37 silly saveTree │ │   │ │ │ │ └── is-buffer@1.1.6
37 silly saveTree │ │   │ │ │ ├── longest@1.0.1
37 silly saveTree │ │   │ │ │ └── repeat-string@1.6.1
37 silly saveTree │ │   │ │ └── lazy-cache@1.0.4
37 silly saveTree │ │   │ ├── right-align@0.1.3
37 silly saveTree │ │   │ └── wordwrap@0.0.2
37 silly saveTree │ │   ├── decamelize@1.2.0
37 silly saveTree │ │   └── window-size@0.1.0
37 silly saveTree │ ├── void-elements@2.0.1
37 silly saveTree │ └─┬ with@4.0.3
37 silly saveTree │   ├── acorn-globals@1.0.9
37 silly saveTree │   └── acorn@1.2.2
37 silly saveTree └─┬ mercadopago@1.0.22
37 silly saveTree   ├── ajv@4.10.3
37 silly saveTree   ├── bluebird@3.4.7
37 silly saveTree   ├─┬ request-etag@2.0.3
37 silly saveTree   │ └── request@2.88.0
37 silly saveTree   ├── request@2.88.0
37 silly saveTree   └── uuid@3.0.1
38 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...nt-env":"latest","gru'
38 verbose stack     at JSON.parse (<anonymous>)
38 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
38 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
38 verbose stack     at processTicksAndRejections (internal/process/next_tick.js:81:5)
39 verbose cwd /Users/quantium/Repos/mercadopago_sample
40 verbose Darwin 18.2.0
41 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/mercadopago/dx-nodejs.git"
42 verbose node v11.10.0
43 verbose npm  v6.9.0
44 error Unexpected end of JSON input while parsing near '...nt-env":"latest","gru'
45 verbose exit [ 1, true ]
```

**Comment by Quantium** [comment]
Hey guys, is there any solution or workaround?

Update: I try with several differente versions of Node and still doesn't work

**Comment by arielfr** [comment]
Hi @Quantium sorry for the late response. This sounds that you have a data corruption in your NPM cache files JSON. See that the error is coming from your local folder of NPM installation:

`/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js`

You can try: `npm cache clean --force`

If not try to uninstall that `global` dependency. If that doesn't work, try manually removing them all just to be sure deleting the global dependencies folder `/usr/local/lib/node_modules/npm/node_modules/`

Let me know if that work

Cheers

**Comment by Quantium** [comment]
😅 Oh! was that, thank you.
