### ISSUE TITLE
How can I get init_point or sandbox_init_point after calling payment.create API?

### ISSUE THREAD

**Issue by rushita-indianic** [mercadopago/dx-nodejs#165]
**Describe the bug**
Have called payment.create API and got json response but couldn't find init_point or sandbox_init_point in response. even no one has created any documentation how to use this documentation to do payment.

**To Reproduce**
```
{
   { id: 2556382,
     date_created: '2017-01-19T17:00:21.000-04:00',
     date_approved: null,
     date_last_updated: '2017-01-19T17:00:21.000-04:00',
     money_release_date: null,
     operation_type: 'regular_payment',
     issuer_id: null,
     payment_method_id: 'rapipago',
     payment_type_id: 'ticket',
     status: 'pending',
     status_detail: 'pending_waiting_payment',
     currency_id: 'ARS',
     description: 'Descripci&oacute;n',
     live_mode: false,
     sponsor_id: null,
     authorization_code: null,
     collector_id: 239656545,
     payer:
      { type: 'guest',
        id: null,
        email: 'test_user_3931694@testuser.com',
        identification: [Object],
        phone: [Object],
        first_name: 'Test',
        last_name: 'Test',
        entity_type: null },
     metadata: {},
     order: {},
     external_reference: null,
     transaction_amount: 10,
     transaction_amount_refunded: 0,
     coupon_amount: 0,
     differential_pricing_id: null,
     deduction_schema: null,
     transaction_details:
      { net_received_amount: 0,
        total_paid_amount: 10,
        overpaid_amount: 0,
        external_resource_url: 'http://www.mercadopago.com/mla/sandbox/payments/ticket/helper?payment_method=rapipago',
        installment_amount: 0,
        financial_institution: null,
        payment_method_reference_id: '2556383' },
     fee_details: [],
     captured: true,
     binary_mode: false,
     call_for_authorize_id: null,
     statement_descriptor: null,
     installments: 1,
     card: {},
     notification_url: null,
     refunds: [] },
  status: 201,
  idempotency: '7fea2db6-fc84-436f-b6f4-457f7f5f151e',
  pagination: undefined
}
```

**Expected behavior**
Now in preference API it is giving two URLs in response to do payment using card/netbanking/center from the near one.

How can I do payment using this response?
**Screenshots**
- NA -

**Comment by LuKks** [comment]
https://www.mercadopago.com.ar/developers/es/guides/payments/api/other-payment-ways

Check the `external_resource_url` but yours seems incomplete, how did you create that payment? Try the example code in the documentation.

**Comment by albert-hoffman** [comment]
@LuKks why it's incomplete? It is coming from APIs I didn't make any self-made changes? we have created payment using npm moduile like this. can you elaborate please how can I get proper URL?

  ```
var payment = {
    description: 'Buying a PS4',
    transaction_amount: 10500,
    payment_method_id: 'rapipago',
    payer: {
      email: 'test_user_3931694@testuser.com',
      identification: {
        type: 'DNI',
        number: '34123123'
      }
    }
  };

   mercadopago.payment.create(payment).then(function (data) {
    res.render('jsonOutput', {
      result: data
    });
  }).catch(function (error) {
    res.render('500', {
      error: error
    });
```

**Comment by LuKks** [comment]
The @rushita-indianic `external_resource_url` is:
http://www.mercadopago.com/mla/sandbox/payments/ticket/helper?payment_method=rapipago

But my url on the response is:
http://www.mercadopago.com/mla/payments/sandbox/ticket/helper?payment_id=22016908&payment_method_reference_id=22016907&caller_id=463597522&hash=c184a56e-f404-414f-ace7-52ccc0eabdd7

That is what I said seems incomplete, so I asked how created that payment. Anyway:

```js
const mp = require('mercadopago');
mp.configure({ access_token: 'TEST-8007196929019694-082120-aed2e0eb866813e28589edb7b5202aa1-463598017' });

mp.payment.create({
  description: 'Buying a PS4',
  transaction_amount: 10500,
  payment_method_id: 'rapipago',
  payer: {
    email: 'test_user_45703644@testuser.com'
  }
})
.then(console.log)
.catch(console.log);
```

The credentials are from https://github.com/mercadopago/dx-nodejs/issues/153#issuecomment-523646539 but I also tested with real credentials, sandbox enabled, etc.

Response with some "irrelevant" parts removed to keep it short:
```js
{
  body: {},
  response: {
    id: 22016908,
    date_created: '2019-10-01T16:00:57.000-04:00',
    operation_type: 'regular_payment',
    payment_method_id: 'rapipago',
    payment_type_id: 'ticket',
    status: 'pending',
    status_detail: 'pending_waiting_payment',
    description: 'Buying a PS4',
    live_mode: false,
    payer: {
      first_name: 'Test',
      last_name: 'Test',
      email: 'test_user_80507629@testuser.com',
      id: '463597522'
    },
    external_reference: null,
    transaction_amount: 10500,
    barcode: {
      type: 'Code128C',
      content: '6001910066005004635975220000220169070010500003',
      width: 1,
      height: 30
    },
    transaction_details: {
      payment_method_reference_id: '22016907',
      total_paid_amount: 10500,
      external_resource_url: 'http://www.mercadopago.com/mla/payments/sandbox/ticket/helper?payment_id=22016908&payment_method_reference_id=22016907&caller_id=463597522&hash=c184a56e-f404-414f-ace7-52ccc0eabdd7',
      verification_code: '22016907'
    },
    captured: true,
    binary_mode: false,
    notification_url: null,
    processing_mode: 'aggregator'
  },
  status: 201,
  idempotency: 'e52adb0c-2121-4767-816c-dd3cf628b016'
}
```

**The user asked "How can I do payment using this response?" also saying that was looking for an `init_point`, the payment method said "rapipago" so the answer would be using the `external_resource_url`.**

**Comment by albert-hoffman** [comment]
@LuKks  thanks for your reply but while I am opening that URL it is not giving me option to do payment using card or net banking. see screenshot, please. I want to do payment then want notification to my URL that what is status of payment.

![image](https://user-images.githubusercontent.com/53006107/66016473-6ccc6b00-e4f4-11e9-9579-7aca77af6556.png)

**Comment by LuKks** [comment]
Due the payment method. That one is called rapipago and accepts only cash, so there is no way to do it online.

For payments trough credit card, in the next url search for `Recibir un pago con tarjeta`:
https://www.mercadopago.com.ar/developers/es/guides/payments/api/receiving-payment-by-card

You are dealing with the API there but you also can work directly with an already built checkout, at this moment there Smart, Mobile or Web Tokenize:
https://www.mercadopago.com.ar/developers/es/guides
https://www.mercadopago.com.ar/developers/es/guides/faqs/integrations

**Comment by albert-hoffman** [comment]
@LuKks how to enable all payment_method? as a user can do payment by any method.

**Comment by LuKks** [comment]
That is a different question. Create a `preference` then use the `init_point` or the `preference id` with Smart Checkout.

Read [/developers/es/guides/payments/web-payment-checkout/introduction](https://www.mercadopago.com.ar/developers/es/guides/payments/web-payment-checkout/introduction)
And later [/developers/es/guides/payments/web-payment-checkout/integration](https://www.mercadopago.com.ar/developers/es/guides/payments/web-payment-checkout/integration)

`init_point`
![image](https://user-images.githubusercontent.com/12686176/66061921-cc3b7280-e516-11e9-8a0d-66290b57db7f.png)
You can see the payment methods.

`Smart Checkout`
Same but integrated in your web instead of external url.

`API`
Can achieve the same but need to build the checkout yourself, it's useful when you want an integrated custom designed checkout.

**Comment by rushita-indianic** [comment]
@LuKks  I used preference API as per your good suggestion. It was really helpful for us. and I got this response which I have attached over here. Now the question is how to get a refund using this response only. kindly give suggestion on refund which property I need to use and which API I need to use, kindly give your information?

```
{
  "processing_modes": [],
  "metadata": {},
  "binary_mode": false,
  "payment_methods": {
    "excluded_payment_methods": [
      {
        "id": ""
      }
    ],
    "excluded_payment_types": [
      {
        "id": ""
      }
    ],
    "installments": null,
    "default_payment_method_id": null,
    "default_installments": null
  },
  "collector_id": 472389951,
  "operation_type": "regular_payment",
  "items": [
    {
      "id": "",
      "picture_url": "",
      "title": "Mojito",
      "description": "Cheesy 8",
      "category_id": "Blah Blah",
      "currency_id": "ARS",
      "quantity": 11,
      "unit_price": 456
    }
  ],
  "payer": {
    "name": "",
    "surname": "",
    "email": "pappu@testuser.com",
    "date_created": "",
    "phone": {
      "area_code": "",
      "number": ""
    },
    "identification": {
      "type": "",
      "number": ""
    },
    "address": {
      "street_name": "",
      "street_number": null,
      "zip_code": ""
    }
  },
  "back_urls": {
    "success": "http://eb7b02b9.ngrok.io/notification/ipn",
    "pending": "http://eb7b02b9.ngrok.io/notification/ipn",
    "failure": "http://eb7b02b9.ngrok.io/notification/ipn"
  },
  "auto_return": "",
  "client_id": "3767495422255439",
  "marketplace": "NONE",
  "marketplace_fee": 0,
  "shipments": {
    "receiver_address": {
      "zip_code": "",
      "street_number": null,
      "street_name": "",
      "floor": "",
      "apartment": ""
    }
  },
  "notification_url": "http://fd7842f1.ngrok.io/notification/ipn",
  "external_reference": "",
  "additional_info": "",
  "expires": false,
  "expiration_date_from": null,
  "expiration_date_to": null,
  "date_created": "2019-10-03T03:35:03.228-04:00",
  "id": "472389951-fdfcf414-18b7-44b3-afd5-5d3cd73fbfc2",
  "init_point": "https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=472389951-fdfcf414-18b7-44b3-afd5-5d3cd73fbfc2",
  "sandbox_init_point": "https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=472389951-fdfcf414-18b7-44b3-afd5-5d3cd73fbfc2"
}
```

**Comment by LuKks** [comment]
In that response you don't have any payment information because the preferences are useful to create the same payment multiple times.

In the `notification_url` you get the payment movements. You can `refund` only with `payment id`:
```js
const mp = require('mercadopago');
mp.configure({ access_token: 'APP_USR-111' });

mp.payment.refund(5227352716)
.then(res => {
  console.log(JSON.stringify(res));
})
.catch(console.log);
```

Response with some "irrelevant" parts removed to keep it short:
```json
{
  "body": {},
  "response": {
    "id": 5227352716,
    "site_id": "MLA",
    "transaction_amount": 40,
    "total_paid_amount": 40,
    "status": "refunded",
    "status_detail": "refunded",
    "installment_amount": 40,
    "payment_type": "credit_card",
    "payment_method_id": "master",
    "operation_type": "recurring_payment",
    "amount_refunded": 40,
    "refunds": [
      {
        "id": 432385015,
        "gtw_refund_id": 11671778874,
        "collection_id": 5227352716,
        "amount": 40,
        "metadata": null,
        "source": {
          "id": "463598017",
          "name": "Test Test",
          "type": "collector"
        },
        "date_created": "2019-10-03T16:06:25.607-04:00"
      }
    ],
    "account_money_amount": 0,
    "cardholder": {
      "name": "APRO",
      "identification": {
        "number": "1111111",
        "type": "DNI"
      }
    },
    "statement_descriptor": "MERCADOPAGO",
    "authorization_code": "1234567",
    "issuer_id": 3,
    "net_received_amount": 38.31,
    "mercadopago_fee": 1.69,
    "notification_url": null,
    "released": "no",
    "collector_id": 463598017,
    "payer": {
      "id": 463597522,
      "email": null
    }
  },
  "status": 200,
  "idempotency": "1bf28028-f581-4269-8175-bffa74cc8ba4"
}
```

**Comment by rushita-indianic** [comment]
@LuKks thanks a lot Lukks you are helping lots. I have tried as per your suggestion but it always showing payment not found.

even the majority gives this error.
![image](https://user-images.githubusercontent.com/55580675/66190684-3a646e80-e6aa-11e9-8bfe-997b6fe93274.png)

**Comment by LuKks** [comment]
Can you send the code that you are using and the response? So I can check the `init_point` and if I get the same error then I can check the code.
One suggestion can be, try to **copy again** the `init_point` and open it from incognito/private mode.

**Comment by rushita-indianic** [comment]
@LuKks  I tried dear, and this is my init_url:
https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=472389951-1487aee6-0f2c-4cce-a41c-b95cb2fef2e3

**Comment by LuKks** [comment]
Yep, your url doesn't work. I already created preferences with my own credentials and everything works perfect for me. Try different account, different credentials, etc.

Why you can't let the complete code?
Instead having and showing unknown variables, you must have constant values to test correctly.

Simple like this:
```js
const mp = require('mercadopago');
mp.configure({ access_token: 'TEST-111' });

mp.preferences.create({
  items: [
    {
      title: 'Buying a PS4',
      unit_price: 10500,
      quantity: 1
    }
  ]
})
.then(console.log)
.catch(console.log);
```

https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=190443805-ff5ff0f6-4da9-44e3-b52d-3290bbf06e75
![image](https://user-images.githubusercontent.com/12686176/66353480-83315700-e938-11e9-8fd9-9937f95026f8.png)

By the way, localhost doesn't work for notifications.

**Comment by rushita-trivedi** [comment]
@LuKks I got this page working now. and I use this code to make payment.

```
const mercadopago = require('mercadopago');
const config = require('../../configs/configs');

mercadopago.configure({
    sandbox: true,
    client_id: config.mercado_pago.client_id,
    client_secret: config.mercado_pago.client_secret,
    access_token: config.mercado_pago.access_token
});

let preference = {
     items: data.items,
     notification_url: "http://524c3219.ngrok.io/api/order/paymentnotification",
     payer: {
        email: data.email,
        identification: {
             type: data.type,
             number: data.number
        }
     }
};

mercadopago.createPreference(preference).then((data) => {
        return exportLib.Response.handleResponse(_this.res, { data: data });
}).catch(function (error) {
        return exportLib.Error.handleError(_this.res, { code: 'INTERNAL_SERVER_ERROR' });
});;

```
The response of creating preference:

```
"response": {
          "processing_modes": [],
          "metadata": {},
          "binary_mode": false,
          "payment_methods": {
              "excluded_payment_methods": [
                  {
                      "id": ""
                  }
              ],
              "excluded_payment_types": [
                  {
                      "id": ""
                  }
              ],
              "installments": null,
              "default_payment_method_id": null,
              "default_installments": null
          },
          "collector_id": 472389951,
          "operation_type": "regular_payment",
          "items": [
              {
                  "id": "",
                  "picture_url": "",
                  "title": "Producto sin descripción",
                  "description": "pen",
                  "category_id": "",
                  "currency_id": "ARS",
                  "quantity": 1,
                  "unit_price": 9
              },
              {
                  "id": "",
                  "picture_url": "",
                  "title": "Producto sin descripción",
                  "description": "papad",
                  "category_id": "",
                  "currency_id": "ARS",
                  "quantity": 2,
                  "unit_price": 10
              }
          ],
          "payer": {
              "name": "",
              "surname": "",
              "email": "",
              "date_created": "",
              "phone": {
                  "area_code": "",
                  "number": ""
              },
              "identification": {
                  "type": "DNI",
                  "number": "47238995"
              },
              "address": {
                  "street_name": "",
                  "street_number": null,
                  "zip_code": ""
              }
          },
          "back_urls": {
              "success": "",
              "pending": "",
              "failure": ""
          },
          "auto_return": "",
          "client_id": "3767495422255439",
          "marketplace": "NONE",
          "marketplace_fee": 0,
          "shipments": {
              "receiver_address": {
                  "zip_code": "",
                  "street_number": null,
                  "street_name": "",
                  "floor": "",
                  "apartment": ""
              }
          },
          "notification_url": "http://524c3219.ngrok.io/api/order/paymentnotification",
          "external_reference": "",
          "additional_info": "",
          "expires": false,
          "expiration_date_from": null,
          "expiration_date_to": null,
          "date_created": "2019-10-09T06:13:57.761-04:00",
          "id": "472389951-3486326e-510b-43c9-a293-a250734156f0",
          "init_point": "https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=472389951-3486326e-510b-43c9-a293-a250734156f0",
          "sandbox_init_point": "https://sandbox.mercadopago.com.ar/checkout/v1/redirect?pref_id=472389951-3486326e-510b-43c9-a293-a250734156f0"
}
```

After using init_point url, I am able to do payment and its success and I got response in notification API. I wrote this code for payment.

response is like this:

```
{
	"action": "payment.created",
	"api_version": "v1",
	"data": {
		"id": "22108569"
	},
	"date_created": "2019-10-09T09:59:35Z",
	"id": 5355204427,
	"live_mode": false,
	"type": "payment",
	"user_id": "472389951"
}
```

then I use this response and use id like it for refund.
`const x = await mercadopago.payment.refund(body.data.id);`

It always gives this error to me.
```
idempotency:"f5bcab0f-9264-45fe-82cf-fa177f80af30"
message:"Unauthorized use of live credentials"
name:"MercadoPagoError"
```
that's why I tried to call this API to get payment details:

const pay_resp = await mercadopago.payment.get(body.data.id);

```
"response": {
		"acquirer": null,
		"acquirer_reconciliation": [],
		"additional_info": {
			"ip_address": "202.131.107.130"
		},
		"authorization_code": null,
		"binary_mode": false,
		"call_for_authorize_id": null,
		"captured": true,
		"card": {
			"cardholder": {
				"identification": {
					"number": "54545645",
					"type": "DNI"
				},
				"name": "Rushita Trivedi"
			},
			"date_created": "2019-10-09T05:59:35.000-04:00",
			"date_last_updated": "2019-10-09T05:59:35.000-04:00",
			"expiration_month": 3,
			"expiration_year": 2022,
			"first_six_digits": "371180",
			"id": null,
			"last_four_digits": "7522"
		},
		"collector_id": 472389951,
		"counter_currency": null,
		"coupon_amount": 0,
		"currency_id": "ARS",
		"date_approved": "2019-10-09T05:59:37.000-04:00",
		"date_created": "2019-10-09T05:59:35.000-04:00",
		"date_last_updated": "2019-10-09T05:59:37.000-04:00",
		"date_of_expiration": null,
		"deduction_schema": null,
		"description": "Producto sin descripción",
		"differential_pricing_id": null,
		"external_reference": null,
		"fee_details": [{
			"amount": 1.22,
			"fee_payer": "collector",
			"type": "mercadopago_fee"
		}],
		"id": 22108569,
		"installments": 1,
		"issuer_id": "2",
		"live_mode": false,
		"marketplace_owner": null,
		"merchant_account_id": null,
		"merchant_number": null,
		"metadata": {},
		"money_release_date": "2019-10-23T05:59:37.000-04:00",
		"money_release_schema": null,
		"notification_url": "http://524c3219.ngrok.io/api/order/paymentnotification",
		"operation_type": "regular_payment",
		"order": {
			"id": "1152872194",
			"type": "mercadopago"
		},
		"payer": {
			"first_name": "Test",
			"last_name": "Test",
			"email": "test_user_80507629@testuser.com",
			"identification": {
				"number": "32659430",
				"type": "DNI"
			},
			"phone": {
				"area_code": "01",
				"number": "1111-1111",
				"extension": ""
			},
			"type": "registered",
			"entity_type": null,
			"id": "474351855"
		},
		"payment_method_id": "amex",
		"payment_type_id": "credit_card",
		"pos_id": null,
		"processing_mode": "aggregator",
		"refunds": [],
		"shipping_amount": 0,
		"sponsor_id": null,
		"statement_descriptor": "KIRANMIK",
		"status": "approved",
		"status_detail": "accredited",
		"store_id": null,
		"taxes_amount": 0,
		"transaction_amount": 29,
		"transaction_amount_refunded": 0,
		"transaction_details": {
			"acquirer_reference": null,
			"external_resource_url": null,
			"financial_institution": null,
			"installment_amount": 29,
			"net_received_amount": 27.78,
			"overpaid_amount": 0,
			"payable_deferral_period": null,
			"payment_method_reference_id": null,
			"total_paid_amount": 29
		}
	}
```
Then It shows this error:

```
idempotency:"1c2cb339-dea4-4a2c-b1fa-bc6a9bdfa458"
message:"Payment not found"
name:"MercadoPagoError"
```

**Comment by LuKks** [comment]
Let's see.

I generated a preference and I used the `init_point`:
```js
const mp = require('mercadopago');

//test seller user (production access token)
mp.configure({
  access_token: 'APP_USR-8007196929019694-082120-d3513f8dd2a0cfb92ac4168d14c0c3cf-463598017'
});

mp.preferences.create({
  items: [
    {
      title: 'Buying a PS4',
      unit_price: 10500,
      quantity: 1
    }
  ],
  payer: {
    //test buyer user (email)
    email: 'test_user_45703644@testuser.com',
    identification: {
      type: 'DNI',
      number: '41111111'
    }
  }
})
.then(console.log)
.catch(console.log);
```

I made the payment process, logged as the test buyer user:
![image](https://user-images.githubusercontent.com/12686176/66516862-6459ce80-eab8-11e9-83c6-7f32b64f33d9.png)
![image](https://user-images.githubusercontent.com/12686176/66516894-789dcb80-eab8-11e9-94a3-f45576c16415.png)

Before I started, I [configured the url notification](https://www.mercadopago.com/mla/account/webhooks) using https://requestbin.com:
![image](https://user-images.githubusercontent.com/12686176/66516053-9702c780-eab6-11e9-82aa-8e2a38874192.png)

So after the payment process, I got this notification:
```json
{
  "action": "payment.created",
  "api_version": "v1",
  "data": {
    "id": "5301122283"
  },
  "date_created": "2019-10-09T20:14:55Z",
  "id": 5355848999,
  "live_mode": true,
  "type": "payment",
  "user_id": "463598017"
}
```

Then I made the refund:
```js
const mp = require('mercadopago');

//test seller user (production access token)
mp.configure({
  access_token: 'APP_USR-8007196929019694-082120-d3513f8dd2a0cfb92ac4168d14c0c3cf-463598017'
});

mp.payment.refund(5301122283) //notification data.id
.then(console.log)
.catch(console.log);
```

The response was something like this:
```json
{
  "body": {},
  "response": {
    "id": 5301122283,
    "site_id": "MLA",
    "reason": "Buying a PS4",
    "currency_id": "ARS",
    "transaction_amount": 10500,
    "total_paid_amount": 10500,
    "status": "refunded",
    "status_detail": "refunded",
    "installment_amount": 10500,
    "payment_type": "credit_card",
    "payment_method_id": "master",
    "operation_type": "regular_payment",
    "amount_refunded": 10500,
    "merchant_order_id": 1153135781,
    "refunds": [
      Object
    ],
    "cardholder": {
      "name": "APRO",
      "identification": Object
    },
    "statement_descriptor": "MERPAGO",
    "authorization_code": "1234567",
    "net_received_amount": 10056.9,
    "mercadopago_fee": 443.1,
    "notification_url": null,
    "released": "no",
    "collector_id": 463598017,
    "payer": {
      "id": 463597522,
      "email": null,
      "phone": Object,
      "identification": Object
    }
  },
  "status": 200,
  "idempotency": "ab60ae30-6162-4c20-8bdf-10233f94fd11"
}
```

By the way, the test users credentials that I used are here: https://github.com/mercadopago/dx-nodejs/issues/153#issuecomment-523646539

**Comment by albert-hoffman** [comment]
@LuKks  I really appreciate your efforts to help us. But don't know why it's showing me Payment not found while doing a refund.
I got this response in notification URL.

```
{
	"action": "payment.created",
	"api_version": "v1",
	"data": {
		"id": "22119198"
	},
	"date_created": "2019-10-10T05:17:31Z",
	"id": 5356610868,
	"live_mode": false,
	"type": "payment",
	"user_id": "472389951"
}
```

In case of your response live_mode: true and for us it's false, is that be an issue?

**Comment by albert-hoffman** [comment]
@LuKks  I am also getting this error sometime:

```
{ MercadoPagoError: Unauthorized use of live credentials
    at Request._callback (/Users/indianic/Desktop/DATABAC/mercado-pago/node/node_modules/mercadopago/lib/request-manager.js:320:19)
    at Request.self.callback (/Users/indianic/Desktop/DATABAC/mercado-pago/node/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/Users/indianic/Desktop/DATABAC/mercado-pago/node/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/Users/indianic/Desktop/DATABAC/mercado-pago/node/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'MercadoPagoError',
  message: 'Unauthorized use of live credentials',
  cause:
   [ { code: 7,
       description: 'Unauthorized use of live credentials',
       data: null } ],
  status: 401,
  idempotency: 'd397afde-27a4-47be-8368-d9d116c73e66' }
```

**Comment by LuKks** [comment]
As I said at the beginning in my previous comment, I used `test users` with `init_point`. You said that you are using the `sandbox_init_point` which definitively is not live mode.

And about the unauthorized error, I think I also got that when I tried an invalid payment id but using correct values you should be fine.
Normally that error indicates you are using wrong the credentials, you must delete `client_id` and `client_secret` and only use the correct `access_token`. Also I think there is no need to use the sandbox boolean in the configuration like my previous examples.

**Comment by albert-hoffman** [comment]
@LuKks you are really supportive and helpful, I am really thankful to you and appreciate your humble help. thanks again.

**Comment by rushita-indianic** [comment]
Thank you so much @LuKks for your help and support. We did the refund successfully as per your guidance. :)
